# Generated by Django 4.1.4 on 2023-05-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('Mercedes-Benz', 'Mercedes Benz'), ('Nissan', 'Nissan'), ('Cadillac', 'Cadillac'), ('Volkswagen', 'Volkswagen Beetle')], default=None, max_length=20)),
                ('manufacturing_date', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.CharField(choices=[('Mercedes-Benz', 'The Mercedes Benz Group'), ('Nissan', 'Nissan Mass Market Cars'), ('Cadillac', 'Cadillac Luxury Vehicles'), (' Volkswagen', 'Volkswagen')], default=None, max_length=20)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black')], default=None, max_length=20)),
            ],
        ),
    ]
